// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUBCKAsWG99CK7_Wp3J3EXWQAFJZfWeWM',
    appId: '1:416750592033:web:30de45dc511927a8860360',
    messagingSenderId: '416750592033',
    projectId: 'samjsevak-14cd2',
    authDomain: 'samjsevak-14cd2.firebaseapp.com',
    storageBucket: 'samjsevak-14cd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZJ34n3yvemONeEm5aaSzXfuaVwrq0iM',
    appId: '1:416750592033:android:3c6a0aa6099654be860360',
    messagingSenderId: '416750592033',
    projectId: 'samjsevak-14cd2',
    storageBucket: 'samjsevak-14cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQS7BsUd7kwohqNt8NMcpq_cSMpeqZuyc',
    appId: '1:416750592033:ios:f06cf30ee59989f6860360',
    messagingSenderId: '416750592033',
    projectId: 'samjsevak-14cd2',
    storageBucket: 'samjsevak-14cd2.appspot.com',
    iosClientId: '416750592033-7f7n5mhvfk4uq0iekt32a1g7si5qnooi.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQS7BsUd7kwohqNt8NMcpq_cSMpeqZuyc',
    appId: '1:416750592033:ios:f06cf30ee59989f6860360',
    messagingSenderId: '416750592033',
    projectId: 'samjsevak-14cd2',
    storageBucket: 'samjsevak-14cd2.appspot.com',
    iosClientId: '416750592033-7f7n5mhvfk4uq0iekt32a1g7si5qnooi.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
